name: Build and Deploy Image-Microservice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        env:
          DOCKER_USER: simon
          DOCKER_PASS: Aprilapril23.
        run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker build --no-cache -t simon/image-microservice:latest .
          docker push simon/image-microservice:latest
